"""Turns the OMOP concept ids of a CEHR-GPT task config into ETHOS CPT4 outcome tokens.

CEHR-GPT task configs (e.g. time_to_event/config/1_year_cabg.yaml) define the outcome as OMOP
concept ids plus `include_descendants`. The tokenized OMOP MEDS data has the procedures as
`CPT4/<concept_code>` tokens, each a single token, so the outcome becomes the CPT4 members of the
expanded concept set:

1. the concept ids are expanded with their descendants in CONCEPT_ANCESTOR (if include_descendants)
2. concepts of other vocabularies (SNOMED, ICD10PCS, ...) that are linked to a CPT4 concept through
   one of --relationships add that CPT4 code
3. the CPT4 concepts are written as `CPT4/<concept_code>` tokens

Usage:
    python scripts/zero_shot/concepts_to_cpt4_tokens.py \
        --task-config ~/cehrgpt/src/cehrgpt/time_to_event/config/1_year_cabg.yaml \
        --vocab-dir /path/to/omop_vocab \
        --cohort cad_cabg_sample > scripts/zero_shot/1_year_cabg.yaml

--vocab-dir holds the Athena tables CONCEPT, CONCEPT_ANCESTOR and CONCEPT_RELATIONSHIP (CSV or
parquet). Pass --tokenized-dir to also list the codes that are not in the model's vocabulary.
"""

import argparse
import sys
from pathlib import Path

import polars as pl
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "omop"))
from build_atc_mapping import scan_athena_table  # noqa: E402

DEFAULT_RELATIONSHIPS = ["SNOMED - CPT4 eq", "SNOMED cat - CPT4", "Maps to", "Mapped from"]


def log(*args):
    print(*args, file=sys.stderr)


def main(args):
    task = yaml.safe_load(Path(args.task_config).expanduser().read_text())
    seeds = [int(c) for c in task["outcome_events"]]
    vocab_dir = Path(args.vocab_dir).expanduser()
    concept = scan_athena_table(vocab_dir, "CONCEPT").select(
        pl.col("concept_id").cast(pl.Int64),
        "concept_name",
        "vocabulary_id",
        "concept_code",
    )

    expanded = set(seeds)
    if task.get("include_descendants", False):
        ancestor = scan_athena_table(vocab_dir, "CONCEPT_ANCESTOR").select(
            pl.col("ancestor_concept_id").cast(pl.Int64),
            pl.col("descendant_concept_id").cast(pl.Int64),
        )
        expanded |= set(
            ancestor.filter(pl.col("ancestor_concept_id").is_in(seeds))
            .select("descendant_concept_id")
            .unique()
            .collect()
            .to_series()
            .to_list()
        )
    members = concept.filter(pl.col("concept_id").is_in(list(expanded))).collect()
    log(f"{len(seeds)} seed concepts -> {members.height} with descendants")
    log(members.group_by("vocabulary_id").len().sort("len", descending=True))

    unknown = set(seeds) - set(members["concept_id"].to_list())
    if unknown:
        raise SystemExit(f"Seed concept ids not in CONCEPT: {sorted(unknown)}")

    cpt4 = members.filter(pl.col("vocabulary_id") == "CPT4")
    others = members.filter(pl.col("vocabulary_id") != "CPT4")["concept_id"].to_list()
    relationship = scan_athena_table(vocab_dir, "CONCEPT_RELATIONSHIP").select(
        pl.col("concept_id_1").cast(pl.Int64),
        pl.col("concept_id_2").cast(pl.Int64),
        "relationship_id",
    )
    linked = (
        relationship.filter(
            pl.col("concept_id_1").is_in(others)
            & pl.col("relationship_id").is_in(args.relationships)
        )
        .join(
            concept.filter(pl.col("vocabulary_id") == "CPT4").lazy(),
            left_on="concept_id_2",
            right_on="concept_id",
        )
        .collect()
    )
    extra = linked.filter(~pl.col("concept_code").is_in(cpt4["concept_code"].to_list()))
    log(
        f"{cpt4.height} CPT4 concepts in the expanded set, "
        f"{extra['concept_code'].n_unique()} more reached through {args.relationships}"
    )
    cpt4 = pl.concat(
        [cpt4, extra.select("concept_id_2", "concept_name", "vocabulary_id", "concept_code").rename(
            {"concept_id_2": "concept_id"})]
    ).unique("concept_code").sort("concept_code")

    # the tokenizer upper-cases codes (CPT4 category II codes end in a letter)
    tokens = [f"CPT4/{code.upper()}" for code in cpt4["concept_code"]]
    if args.tokenized_dir:
        from ethos.vocabulary import Vocabulary

        vocab = Vocabulary.from_path(Path(args.tokenized_dir))
        absent = [t for t in tokens if t not in vocab.stoi]
        log(f"{len(absent)} of {len(tokens)} tokens are not in the vocab: {absent}")

    window = task.get("prediction_window_end", -1)
    horizon = args.time_limit_days if args.time_limit_days is not None else window
    if horizon in (None, -1):
        raise SystemExit("The task config has no prediction_window_end, pass --time-limit-days")

    print(f"# Generated by scripts/zero_shot/concepts_to_cpt4_tokens.py from {Path(args.task_config).name}")
    print(f"# ({len(seeds)} OMOP concept ids, descendants: {task.get('include_descendants', False)}).")
    print(f"# One CPT4 token per code of the expanded concept set; run_zero_shot.py drops the ones")
    print("# that are not in the model's vocabulary and says so.")
    print(f"{args.cohort}:")
    print("  outcome_stokens:")
    for token, name in zip(tokens, cpt4["concept_name"]):
        print(f"    - {token}  # {name[:80].replace(chr(10), ' ')}")
    print(f"  time_limit_days: {horizon}")
    print("  strict_cutoff: false")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--task-config", required=True, help="CEHR-GPT time_to_event task yaml")
    parser.add_argument("--vocab-dir", required=True, help="folder with the OMOP vocabulary tables")
    parser.add_argument("--cohort", required=True, help="cohort folder name, e.g. cad_cabg_sample")
    parser.add_argument("--tokenized-dir", help="tokenized split, to check the codes against its vocab")
    parser.add_argument("--time-limit-days", type=int, help="default: prediction_window_end")
    parser.add_argument("--relationships", nargs="*", default=DEFAULT_RELATIONSHIPS)
    main(parser.parse_args())
